apiVersion: v1
kind: Service
metadata:
  name: {{ include "flashbake-relay.fullname" . }}
  labels:
    {{- include "flashbake-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10732
      protocol: TCP
      name: rpc
  selector:
    {{- include "flashbake-relay.selectorLabels" . | nindent 4 }}
