name: publish

on: [push]

jobs:
  publish-to-ghcr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Login to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Docker meta relay
      id: meta-relay
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/flashbake-relay
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=match,pattern=v(.*),group=1

    - name: Docker meta endpoint
      id: meta-endpoint
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/flashbake
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=match,pattern=v(.*),group=1
    - name: Push flashbake endpoint container to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta-endpoint.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: flashbake

    - name: Push flashbake relay container to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta-relay.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: flashbake-relay
